src/Entity/WebScrapingRequest.php
<?php

namespace App\Entity;

use App\Config\WebScrapingRequestStatusType;
use App\Repository\WebScrapingRequestRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: WebScrapingRequestRepository::class)]
class WebScrapingRequest
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?DateTimeImmutable $created_at = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $navigate_url = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $webhook_url = null;

    #[ORM\Column(type: 'web_scraping_request_status')]
    private $status = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $consumed_screenshot = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $consumed_content = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $consumed_url = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $consumed_remote_status = null;

    #[ORM\Column(type: 'web_scraping_request_completed_handle', nullable: true)]
    private $completed_handle = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $steps = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $last_error_message = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $consumed_at = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $xhrlog = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cache_hash = null;

    #[ORM\Column(nullable: true)]
    private ?int $filtered_items_count = null;

    #[ORM\Column(nullable: true)]
    private ?int $extracted_items_count = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getNavigateUrl(): ?string
    {
        return $this->navigate_url;
    }

    public function setNavigateUrl(string $navigate_url): static
    {
        $this->navigate_url = $navigate_url;

        return $this;
    }

    public function getWebhookUrl(): ?string
    {
        return $this->webhook_url;
    }

    public function setWebhookUrl(string $webhook_url): static
    {
        $this->webhook_url = $webhook_url;

        return $this;
    }

    public function getStatus()
    {
        return $this->status;
    }

    public function setStatus($status): static
    {
        $this->status = $status;

        return $this;
    }

    #[ORM\PrePersist]
    private function prePersist(): void
    {
        if ($this->getStatus() === NULL) {
            $this->setStatus(WebScrapingRequestStatusType::NEWLY_CREATED);
        }
        if ($this->getCreatedAt() === NULL) {
            $this->setCreatedAt(new DateTimeImmutable());
        }
    }

    public function getConsumedScreenshot(): ?string
    {
        return $this->consumed_screenshot;
    }

    public function setConsumedScreenshot(?string $consumed_screenshot): static
    {
        $this->consumed_screenshot = $consumed_screenshot;

        return $this;
    }

    public function getConsumedContent(): ?string
    {
        return $this->consumed_content;
    }

    public function setConsumedContent(string $consumed_content): static
    {
        $this->consumed_content = $consumed_content;

        return $this;
    }

    public function getConsumedUrl(): ?string
    {
        return $this->consumed_url;
    }

    public function setConsumedUrl(string $consumed_url): static
    {
        $this->consumed_url = $consumed_url;

        return $this;
    }

    public function getConsumedRemoteStatus(): ?string
    {
        return $this->consumed_remote_status;
    }

    public function setConsumedRemoteStatus(string $consumed_remote_status): static
    {
        $this->consumed_remote_status = $consumed_remote_status;

        return $this;
    }

    public function getCompletedHandle()
    {
        return $this->completed_handle;
    }

    public function setCompletedHandle($completed_handle): static
    {
        $this->completed_handle = $completed_handle;

        return $this;
    }

    public function getSteps(): ?string
    {
        return $this->steps;
    }

    public function setSteps(?string $steps): static
    {
        $this->steps = $steps;

        return $this;
    }

    public function getLastErrorMessage(): ?string
    {
        return $this->last_error_message;
    }

    public function setLastErrorMessage(?string $last_error_message): static
    {
        $this->last_error_message = $last_error_message;

        return $this;
    }

    public function getConsumedAt(): ?\DateTimeImmutable
    {
        return $this->consumed_at;
    }

    public function setConsumedAt(?\DateTimeImmutable $consumed_at): static
    {
        $this->consumed_at = $consumed_at;

        return $this;
    }

    public function getXhrlog(): ?string
    {
        return $this->xhrlog;
    }

    public function setXhrlog(?string $xhrlog): static
    {
        $this->xhrlog = $xhrlog;

        return $this;
    }

    public function getCacheHash(): ?string
    {
        return $this->cache_hash;
    }

    public function setCacheHash(?string $cache_hash): static
    {
        $this->cache_hash = $cache_hash;

        return $this;
    }

    public static function prepareCacheHash(WebScrapingRequest $webScrapingRequest): string
    {
        $hashParams = [
            $webScrapingRequest->getNavigateUrl() ?? 'NULL',
            $webScrapingRequest->getSteps() ?? 'NULL',
            $webScrapingRequest->getWebhookUrl() ?? 'NULL',
            $webScrapingRequest->getCompletedHandle() ?? 'NULL',
        ];
        return md5(implode("-", $hashParams));
    }

    public function getFilteredItemsCount(): ?int
    {
        return $this->filtered_items_count;
    }

    public function setFilteredItemsCount(?int $filtered_items_count): static
    {
        $this->filtered_items_count = $filtered_items_count;

        return $this;
    }

    public function getExtractedItemsCount(): ?int
    {
        return $this->extracted_items_count;
    }

    public function setExtractedItemsCount(?int $extracted_items_count): static
    {
        $this->extracted_items_count = $extracted_items_count;

        return $this;
    }

}

src/Controller/Admin/Table/WebScrapingRequestTable.php
<?php namespace App\Controller\Admin\Table;

use App\Config\NotificationPriorityType;
use App\Config\WebScrapingRequestStatusType;
use App\Entity\Notification;
use App\Entity\SubscriptionPlan;
use App\Entity\User;
use App\Entity\WebScrapingRequest;
use App\Service\CrudTable\ActionsColumn;
use App\Service\CrudTable\BadgeColumn;
use App\Service\CrudTable\CrudTableAction;
use App\Service\CrudTable\DisableCachingCriteriaProvider;
use App\Service\CrudTable\FormattedDateTimeColumn;
use App\Service\CrudTable\ShowMoreTextColumn;
use DateTime;
use Doctrine\ORM\QueryBuilder;
use Omines\DataTablesBundle\Adapter\Doctrine\ORM\SearchCriteriaProvider;
use Omines\DataTablesBundle\Adapter\Doctrine\ORMAdapter;
use Omines\DataTablesBundle\Column\TextColumn;
use Omines\DataTablesBundle\DataTable;
use Omines\DataTablesBundle\DataTableTypeInterface;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class WebScrapingRequestTable extends TableAbstractController implements DataTableTypeInterface
{

    public function configure(DataTable $dataTable, array $options): void
    {
        $dataTable->add('created_at', FormattedDateTimeColumn::class, [
            'label' => $this->t("Zaman Damgası"),
            'orderable' => TRUE
        ]);
        $dataTable->add('navigate_url', ShowMoreTextColumn::class, [
            'label' => $this->t("URL"),
            'orderable' => FALSE
        ]);
        $dataTable->add('steps', BadgeColumn::class, [
            'label' => $this->t("Adımlar"),
            'className' => "text-center",
            'orderable' => FALSE,
            'type' => function ($theValue) {
                return $theValue === NULL ? 'light' : 'primary';
            },
            'content' => function ($theValue) {
                $badgeText = "--";
                $decodedJSON = is_string($theValue) ? json_decode($theValue) : NULL;
                if (is_array($decodedJSON)) {
                    $stepsCount = count($decodedJSON);
                    $badgeText = $stepsCount . " " . $this->t("adet");
                }
                return $badgeText;
            }
        ]);
        $dataTable->add('consumed_at', FormattedDateTimeColumn::class, [
            'label' => $this->t("Süre"),
            'className' => "text-center",
            'orderable' => FALSE,
            'render' => function ($theValue, $theContext) {
                if ($theContext->getConsumedAt() !== NULL && $theContext->getCreatedAt() !== NULL) {
                    $timeDiffSec = $theContext->getConsumedAt()->getTimestamp() - $theContext->getCreatedAt()->getTimestamp();
                    return '<i class="bx bxs-watch"></i> <sup>' . $timeDiffSec . $this->t("sn") . "</sup>";
                }
                return '<div class="spinner-border spinner-border-sm text-secondary" role="status"><span class="visually-hidden">Loading...</span></div>';
            }
        ]);
        $dataTable->add('status', BadgeColumn::class, [
            'label' => $this->t("Durum"),
            'className' => "text-center",
            'orderable' => FALSE,
            'type' => function ($theValue) {
                if ($theValue === WebScrapingRequestStatusType::COMPLETED) {
                    return "success";
                }
                return "secondary";
            },
            'content' => function ($theValue) {
                return $theValue;
            }
        ]);
        $dataTable->add('id', ActionsColumn::class, [
            'actions' => [
                function ($value, UrlGeneratorInterface $urlGenerator) {
                    $gotoURL = $urlGenerator->generate('app_administrator_web_scraping_request_delete', ['webScrapingRequest' => $value]);
                    return new CrudTableAction($this->t("Sil"), $gotoURL, 'bx bx-trash');
                },
                function ($value, UrlGeneratorInterface $urlGenerator) {
                    $gotoURL = $urlGenerator->generate('app_administrator_web_scraping_request_show_html', ['webScrapingRequest' => $value]);
                    return new CrudTableAction($this->t("İçeriği Görüntüle"), $gotoURL, 'bx bxs-file-html');
                },
            ]
        ]);

        $dataTable->createAdapter(ORMAdapter::class, [
            'entity' => WebScrapingRequest::class,
            'criteria' => [
                new DisableCachingCriteriaProvider(),
                new SearchCriteriaProvider(),
            ],
            'query' => function (QueryBuilder $builder) {
                $builder
                    ->select('x')
                    ->from(WebScrapingRequest::class, 'x');
            },
        ]);

        // Add Default Order
        // $dataTable->addOrderBy("planOrder", self::DEFAULT_ORDER_DIRECTION_CREATED_AT);

    }


}

src/Controller/Administrator/DashboardController.php
<?php namespace App\Controller\Administrator;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_ADMIN')]
#[Route('/administrator', name: 'app_administrator_')]
class DashboardController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(): Response
    {
        return $this->render('administrator/dashboard/index.html.twig');
    }

}

src/Controller/Administrator/ProductController.php
<?php namespace App\Controller\Administrator;

use App\Controller\Admin\Table\ProductTable;
use App\Entity\Product;
use App\Service\CrudTable\CrudTableService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_ADMIN')]
#[Route('/administrator/product', name: 'app_administrator_product_')]
class ProductController extends AbstractController
{
    #[Route('/', name: 'index', methods: ['GET'])]
    public function index(Request $request, CrudTableService $crudTableService): Response
    {
        $webScrapingRequestTable = $crudTableService->createFromFQCN($request, ProductTable::class);
        return $this->render('administrator/product/index.html.twig', [
            'productTable' => $webScrapingRequestTable,
        ]);
    }

    #[Route('/go_to_product/{theProduct}', name: 'go_to_product')]
    public function goToProduct(Product $theProduct): RedirectResponse
    {
        return $this->redirect($theProduct->getUrl());
    }

    #[Route('/go_to_product_marketplace/{theProduct}', name: 'go_to_product_marketplace')]
    public function goToProductMarketplace(Product $theProduct): RedirectResponse
    {
        return $this->redirect($theProduct->getMarketplace()->getUrl());
    }

}

src/Controller/Administrator/SubscriptionPlanController.php
<?php namespace App\Controller\Administrator;

use App\Controller\Admin\Table\SubscriptionPlanTable;
use App\Entity\SubscriptionPlan;
use App\Form\Administrator\SubscriptionPlanType;
use App\Repository\UserRepository;
use App\Service\CrudTable\CrudTableService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use function Symfony\Component\Translation\t;

#[IsGranted('ROLE_ADMIN')]
#[Route('/administrator/subscription/plan', name: 'app_administrator_subscription_plan_')]
class SubscriptionPlanController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(Request $request, CrudTableService $crudTableService): Response
    {
        $subscriptionPlanTable = $crudTableService->createFromFQCN($request, SubscriptionPlanTable::class);
        return $this->render('administrator/subscription_plan/index.html.twig', [
            'subscriptionPlanTable' => $subscriptionPlanTable,
        ]);
    }

    #[Route('/delete/{subscriptionPlan}', name: 'delete')]
    public function delete(SubscriptionPlan $subscriptionPlan, EntityManagerInterface $entityManager, UserRepository $userRepository): Response
    {
        $planUserExist = $userRepository->findOneBy(["subscription_plan" => $subscriptionPlan]);
        if ($planUserExist === NULL) {
            $entityManager->remove($subscriptionPlan);
            $entityManager->flush();
            $this->addFlash('pageNotificationSuccess', t("Abonelik planı başarıyla silindi."));
        } else {
            $this->addFlash('pageNotificationError', t("Bu abonelik planını halen kullanan kullanıcılar olduğu için plan silinemiyor."));
        }

        return $this->redirectToRoute('app_administrator_subscription_plan_index');
    }

    #[Route('/new', name: 'new')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $subscriptionPlan = new SubscriptionPlan();
        $form = $this->createForm(SubscriptionPlanType::class, $subscriptionPlan);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($subscriptionPlan);
            $entityManager->flush();

            return $this->redirectToRoute('app_administrator_subscription_plan_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('administrator/subscription_plan/new.html.twig', [
            'subscription_plan' => $subscriptionPlan,
            'form' => $form,
        ]);
    }
}

src/Controller/Administrator/UserController.php
<?php namespace App\Controller\Administrator;

use App\Controller\Admin\Table\UserTable;
use App\Service\CrudTable\CrudTableService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_ADMIN')]
#[Route('/administrator/user', name: 'app_administrator_user_')]
class UserController extends AbstractController
{

    #[Route('/', name: 'index')]
    public function index(Request $request, CrudTableService $crudTableService): Response
    {
        $userTable = $crudTableService->createFromFQCN($request, UserTable::class);
        return $this->render('administrator/user/index.html.twig', [
            'userTable' => $userTable,
        ]);
    }

}

templates/administrator/web_scraping_request/index.html.twig
{% extends 'layout/admin.html.twig' %}

{% block pageTitle %}{{ 'Yönetici Paneli / Web Kazıma İstekleri'|trans }}{% endblock %}
{% block contentTitle %}{{ 'Yönetici Paneli / Web Kazıma İstekleri'|trans }}{% endblock %}

{% block pageActions %}
    <div class="btn-group" role="group">
        <a href="{{ path('app_administrator_web_scraping_request_new_by_url') }}" class="btn btn-secondary">{{ 'URL Ekle'|trans }}</a>
        <a href="{{ path('app_administrator_web_scraping_request_new') }}" class="btn btn-secondary">{{ 'Rastgele Ekle'|trans }}</a>
        <a href="{{ path('app_administrator_web_scraping_request_delete_all') }}" class="btn btn-danger">{{ 'Tümünü Sil'|trans }}</a>
    </div>
{% endblock %}

{% block body %}

    {{ component('_crud_table_component', { table: webScrapingRequestTable, title: 'Web Kazıma İstekleri'|trans}) }}

{% endblock %}

templates/administrator/web_scraping_request/new.html.twig
{% extends 'layout/admin.html.twig' %}

{% block pageTitle %}{{ 'Yönetici Paneli / Web Kazıma İstekleri'|trans }}{% endblock %}
{% block contentTitle %}{{ 'Yönetici Paneli / Web Kazıma İstekleri'|trans }}{% endblock %}

{% block pageActions %}
    <a href="{{ path('app_administrator_web_scraping_request_index') }}" class="btn btn-secondary">{{ 'Listeye Geri Dön'|trans }}</a>
{% endblock %}

{% block body %}

    <div class="card">
        <div class="card-body">
            {{ include('administrator/web_scraping_request/_form.html.twig') }}
        </div>
    </div>

{% endblock %}

templates/administrator/web_scraping_request/show_html.html.twig
{% extends 'layout/admin.html.twig' %}

{% block pageTitle %}{{ 'Yönetici Paneli / Web Kazıma İstekleri'|trans }}{% endblock %}
{% block contentTitle %}{{ 'Yönetici Paneli / Web Kazıma İstekleri'|trans }}{% endblock %}

{% block pageActions %}

    <div class="btn-group" role="group">
        <a href="{{ path('app_administrator_web_scraping_request_content_iframe', {webScrapingRequest: webScrapingRequest.id}) }}" class="btn btn-secondary" target="_blank">{{ 'Yeni Pencerede Aç'|trans }}</a>
        <a href="{{ path('app_administrator_web_scraping_request_index') }}" class="btn btn-secondary">{{ 'Listeye Geri Dön'|trans }}</a>
    </div>

{% endblock %}

{% block body %}

    {% if webScrapingRequest.status is same as('COMPLETED') %}

        <div class="nav-align-top">
            <ul class="nav nav-tabs" role="tablist">

                <!-- Status -->
                <li class="nav-item" >
                    <button type="button" class="nav-link disabled" role="tab" data-bs-toggle="tab" data-bs-target="#navs-screenshot" aria-controls="navs-screenshot" aria-selected="true">
                        <i class="bx bx-hash"></i>
                        {{ webScrapingRequest.id }}
                        {% if webScrapingRequest.filteredItemsCount is not same as(null) and webScrapingRequest.extractedItemsCount is not same as(null) %}
                            <sup>
                                {{ webScrapingRequest.filteredItemsCount }}/{{ webScrapingRequest.extractedItemsCount }}
                            </sup>
                        {% endif %}
                    </button>
                </li>

                <!-- Screenshot -->
                {% if webScrapingRequest.consumedScreenshot is not same as(null) %}
                    <li class="nav-item">
                        <button type="button" class="nav-link active" role="tab" data-bs-toggle="tab" data-bs-target="#navs-screenshot" aria-controls="navs-screenshot" aria-selected="true">
                            {{ 'Ekran Görüntüsü'|trans }}
                        </button>
                    </li>
                {% endif %}

                <!-- Consumed Content Frame -->
                {% if webScrapingRequest.consumedContent is not same as(null) %}
                    <li class="nav-item">
                        <button type="button" class="nav-link" role="tab" data-bs-toggle="tab" data-bs-target="#navs-content" aria-controls="navs-content" aria-selected="false">
                            {{ 'Sayfa İçeriği'|trans }}
                        </button>
                    </li>
                {% endif %}

                <!-- XHR Log -->
                {% if webScrapingRequest.xhrlog is not same as(null) %}
                    <li class="nav-item">
                        <button type="button" class="nav-link" role="tab" data-bs-toggle="tab" data-bs-target="#navs-xhrlog" aria-controls="navs-xhrlog" aria-selected="false">
                            {{ 'XHR Kayıtları'|trans }}
                        </button>
                    </li>
                {% endif %}

                <!-- Steps -->
                {% if webScrapingRequest.xhrlog is not same as(null) %}
                    <li class="nav-item">
                        <button type="button" class="nav-link" role="tab" data-bs-toggle="tab" data-bs-target="#navs-steps" aria-controls="navs-steps" aria-selected="false">
                            {{ 'Adımlar'|trans }}
                        </button>
                    </li>
                {% endif %}

            </ul>
            <div class="tab-content">

                <!-- Screenshot -->
                {% if webScrapingRequest.consumedScreenshot is not same as(null) %}
                    <div class="tab-pane fade show active" id="navs-screenshot" role="tabpanel">
                        <img class="card-img" src="data:image/png;base64, {{ webScrapingRequest.consumedScreenshot|raw }}" alt="{{ 'Ekran Görüntüsü'|trans }}">
                    </div>
                {% endif %}

                <!-- Consumed Content Frame -->
                {% if webScrapingRequest.consumedContent is not same as(null) %}
                    <div class="tab-pane fade" id="navs-content" role="tabpanel">
                        {% if decodedContent is not same as(false) and webScrapingRequest.status is same as("COMPLETED") %}
                            <iframe src="{{ path('app_administrator_web_scraping_request_content_iframe', { webScrapingRequest: webScrapingRequest.id }) }}" style="width: 100%; height: 600px;" class="chat-history-body" sandbox="allow-scripts"></iframe>
                        {% else %}
                            <div class="alert alert-danger" role="alert">
                                {{ 'Bu içerik çözümlenemedi ya da henüz tamamlanmadı.' }}
                            </div>
                        {% endif %}
                    </div>
                {% endif %}

                <!-- XHR Log -->
                {% if webScrapingRequest.xhrlog is not same as(null) %}
                    <div class="tab-pane fade" id="navs-xhrlog" role="tabpanel">
                       <pre>
                            <code class="language-json">{{ webScrapingRequest.xhrlog|json_pretty_print|escape }}</code>
                       </pre>
                    </div>
                {% endif %}

                <!-- Steps -->
                {% if webScrapingRequest.steps is not same as(null) %}
                    <div class="tab-pane fade" id="navs-steps" role="tabpanel">
                        <pre>
                            <code class="language-json">{{ webScrapingRequest.steps|json_pretty_print|escape }}</code>
                        </pre>
                    </div>
                {% endif %}

            </div>
        </div>

        {% else %}
        <div class="row">
            <div class="alert alert-danger" role="alert">
                {{ 'Bu veri çekme isteği henüz tamamlanmadı.'|trans }}
            </div>
            {% if webScrapingRequest.lastErrorMessage is not same as(null) %}
                <div class="alert alert-danger" role="alert">
                    {{ webScrapingRequest.lastErrorMessage|trans }}
                </div>
            {% endif %}
        </div>
    {% endif %}

{% endblock %}