src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use function Symfony\Component\Translation\t;

#[ORM\HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'Bu e-posta adresiyle zaten daha önce kayıt yapılmış')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $display_name = null;

    /* DEPRECED
    #[Assert\Expression(
        "!(this.getPhone() contains ' ')",
        message: 'Telefon numaranızı hiçbir boşluk karakteri olmadan giriniz. Örn; +905555555555',
    )]
    #[Assert\Expression(
        "this.getPhone() starts with '+'",
        message: 'Telefon numarası + işaretiyle başlamalıdır. Lütfen telefon numaranızı ülke koduyla beraber yazın. Örn; +905555555555',
    )]
    #[Assert\Length(
        min: 10,
        max: 16,
    )]*/
    #[ORM\Column(length: 20, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(nullable: true)]
    private ?DateTimeImmutable $created_at = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToMany(targetEntity: TeamInvite::class, mappedBy: 'user')]
    private Collection $teamInvites;

    #[ORM\OneToMany(targetEntity: AbstractFile::class, mappedBy: 'uploaded_by')]
    private Collection $abstractFiles;

    #[ORM\Column(nullable: true)]
    private ?bool $dark_mode = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $locale = null;

    #[ORM\OneToMany(targetEntity: Notification::class, mappedBy: 'to_user')]
    private Collection $notifications;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Team $team = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_passive = null;

    #[ORM\OneToMany(targetEntity: UserActivity::class, mappedBy: 'user')]
    private Collection $userActivities;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $preferred_theme = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $last_login = null;

    #[ORM\ManyToOne]
    private ?SubscriptionPlan $subscription_plan = null;

    #[ORM\Column(nullable: true)]
    private ?bool $trial_period_used = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $subscription_plan_valid_until = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $last_ip_address = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?UserPreferences $preferences = null;

    public function __construct()
    {
        $this->teamInvites = new ArrayCollection();
        $this->abstractFiles = new ArrayCollection();
        $this->notifications = new ArrayCollection();
        $this->userActivities = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getDisplayName(): ?string
    {
        return $this->display_name;
    }

    public function setDisplayName(?string $display_name): static
    {
        $this->display_name = $display_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(?DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    #[ORM\PrePersist]
    public function setPrePersistValues(): void
    {
        // Set - Created At
        if ($this->created_at === NULL) {
            $this->created_at = new DateTimeImmutable();
        }
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function setDefaults(): static
    {
        // Set Default Roles
        $this->setRoles(["ROLE_USER"]);
        $this->setDarkMode(FALSE);

        return $this;
    }

    /**
     * @return Collection<int, TeamInvite>
     */
    public function getTeamInvites(): Collection
    {
        return $this->teamInvites;
    }

    public function addTeamInvite(TeamInvite $teamInvite): static
    {
        if (!$this->teamInvites->contains($teamInvite)) {
            $this->teamInvites->add($teamInvite);
            $teamInvite->setUser($this);
        }

        return $this;
    }

    public function removeTeamInvite(TeamInvite $teamInvite): static
    {
        if ($this->teamInvites->removeElement($teamInvite)) {
            // set the owning side to null (unless already changed)
            if ($teamInvite->getUser() === $this) {
                $teamInvite->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, AbstractFile>
     */
    public function getAbstractFiles(): Collection
    {
        return $this->abstractFiles;
    }

    public function addAbstractFile(AbstractFile $abstractFile): static
    {
        if (!$this->abstractFiles->contains($abstractFile)) {
            $this->abstractFiles->add($abstractFile);
            $abstractFile->setUploadedBy($this);
        }

        return $this;
    }

    public function removeAbstractFile(AbstractFile $abstractFile): static
    {
        if ($this->abstractFiles->removeElement($abstractFile)) {
            // set the owning side to null (unless already changed)
            if ($abstractFile->getUploadedBy() === $this) {
                $abstractFile->setUploadedBy(null);
            }
        }

        return $this;
    }

    public function isDarkMode(): ?bool
    {
        return $this->dark_mode;
    }

    public function setDarkMode(?bool $dark_mode): static
    {
        $this->dark_mode = $dark_mode;

        return $this;
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(?string $locale): static
    {
        $this->locale = $locale;

        return $this;
    }

    /**
     * @return Collection<int, Notification>
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): static
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications->add($notification);
            $notification->setToUser($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): static
    {
        if ($this->notifications->removeElement($notification)) {
            // set the owning side to null (unless already changed)
            if ($notification->getToUser() === $this) {
                $notification->setToUser(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return ($this->getDisplayName() !== NULL) ? $this->getDisplayName() : $this->getEmail();
    }

    public function getTeam(): ?Team
    {
        return $this->team;
    }

    public function setTeam(?Team $team): static
    {
        $this->team = $team;

        return $this;
    }

    public function isIsPassive(): ?bool
    {
        return $this->is_passive;
    }

    public function setIsPassive(?bool $is_passive): static
    {
        $this->is_passive = $is_passive;

        return $this;
    }

    /**
     * @return Collection<int, UserActivity>
     */
    public function getUserActivities(): Collection
    {
        return $this->userActivities;
    }

    public function addUserActivity(UserActivity $userActivity): static
    {

templates/layout/partials/_admin_bar.html.twig
{% if is_granted('ROLE_ADMIN') %}
    {{ include('layout/partials/_administrator.html.twig') }}
{% endif %}

templates/layout/partials/_administrator.html.twig
<!-- Administrator Bar  -->
<li class="nav-item dropdown-shortcuts navbar-dropdown dropdown me-2 me-xl-0">
    <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
        <i class="bx bx-code-alt bx-sm text-danger"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-end py-0">
        <div class="dropdown-menu-header border-bottom">
            <div class="dropdown-header d-flex align-items-center py-3">
                <h5 class="text-body mb-0 me-auto">{{ 'Yönetim Paneli'|trans }}</h5>
                <a href="{{ path('app_administrator_index') }}" class="dropdown-shortcuts-add text-body" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ 'Genel Bakış'|trans }}"><i class="bx bx-sm bx-line-chart-down"></i></a>
            </div>
        </div>
        <div class="dropdown-shortcuts-list scrollable-container">
            <div class="row row-bordered overflow-visible g-0">
                <div class="dropdown-shortcuts-item col">
                    <span class="dropdown-shortcuts-icon bg-label-secondary rounded-circle mb-2">
                        <i class="bx bx-user fs-4"></i>
                    </span>
                    <a href="{{ path('app_administrator_user_index') }}" class="stretched-link">
                        {{ 'Kullanıcılar'|trans }}
                    </a>
                    <small class="text-muted mb-0">
                        {{ 'Tablo'|trans }}
                    </small>
                </div>
                <div class="dropdown-shortcuts-item col">
                    <span class="dropdown-shortcuts-icon bg-label-secondary rounded-circle mb-2">
                        <i class="bx bx-rocket fs-4"></i>
                    </span>
                    <a href="{{ path('app_administrator_subscription_plan_index') }}" class="stretched-link">
                        {{ 'Abonelik Planları'|trans }}
                    </a>
                    <small class="text-muted mb-0">
                        {{ 'Tablo'|trans }}
                    </small>
                </div>
            </div>
            <div class="row row-bordered overflow-visible g-0">
                <div class="dropdown-shortcuts-item col">
                    <span class="dropdown-shortcuts-icon bg-label-secondary rounded-circle mb-2">
                        <i class="bx bx-store-alt fs-4"></i>
                    </span>
                    <a href="{{ path('app_administrator_product_index') }}" class="stretched-link">
                        {{ 'Ürünler'|trans }}
                    </a>
                    <small class="text-muted mb-0">
                        {{ 'Tablo'|trans }}
                    </small>
                </div>
                <div class="dropdown-shortcuts-item col">
                    <span class="dropdown-shortcuts-icon bg-label-secondary rounded-circle mb-2">
                        <i class="bx bx-help-circle fs-4"></i>
                    </span>
                    <a href="#" class="stretched-link">
                        {{ 'Yardım Merkezi'|trans }}
                    </a>
                    <small class="text-muted mb-0">
                        {{ 'Tablo'|trans }}
                    </small>
                </div>
            </div>
            <div class="row row-bordered overflow-visible g-0">
                <div class="dropdown-shortcuts-item col">
                    <span class="dropdown-shortcuts-icon bg-label-secondary rounded-circle mb-2">
                        <i class="bx bx-store fs-4"></i>
                    </span>
                    <a href="{{ path('app_administrator_marketplace_index') }}" class="stretched-link">
                        {{ 'Pazaryerleri'|trans }}
                    </a>
                    <small class="text-muted mb-0">
                        {{ 'Tablo'|trans }}
                    </small>
                </div>
                <div class="dropdown-shortcuts-item col">
                    <span class="dropdown-shortcuts-icon bg-label-secondary rounded-circle mb-2">
                        <i class="bx bxl-chrome fs-4"></i>
                    </span>
                    <a href="{{ path('app_administrator_web_scraping_request_index') }}" class="stretched-link">
                        {{ 'Kazıma İstekleri'|trans }}
                    </a>
                    <small class="text-muted mb-0">
                        {{ 'Tablo'|trans }}
                    </small>
                </div>
            </div>
        </div>
    </div>
</li>
<!-- Administrator Bar -->

templates/layout/partials/_file_sharing.html.twig
<li class="nav-item dropdown-style-switcher dropdown me-2 me-xl-0">
    <a class="nav-link hide-arrow" href="{{ path('app_admin_file_sharing_index') }}">
        <i class="bx bx-sm bx-cloud-upload"></i>
    </a>
</li>

templates/layout/partials/_footer.html.twig
<div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
    <div class="mb-2 mb-md-0">
        © {{ 'now' | date('Y') }}, made with ❤️ by
        <a href="{{ layout.admin.developer.url }}" target="_blank" class="footer-link fw-medium">{{ layout.admin.developer.name }}</a>
    </div>
    <div class="d-none d-lg-inline-block">
        <a href="{{ path(layout.admin.developer.helpCenterPath) }}" class="footer-link me-4">
            {{ 'Yardım Merkezi'|trans }}
        </a>
        <span class="badge rounded-pill bg-label-secondary">
            {{ app.request.locale|upper }}
        </span>
    </div>
</div>

templates/layout/partials/_head.html.twig
{% for meta in layout.admin.meta %}
    <meta name="{{ meta.name }}" content="{{ meta.content }}" />
{% endfor %}

<!-- Favicon -->
<link rel="icon" type="image/x-icon" href="{{ asset(layout.admin.favicon) }}" />

<!-- Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet" />

<!-- Core Stylesheets -->
{% set isDarkModed = (app.user is not same as(null)) and (app.user.darkMode is same as(true)) %}
{% block appStylesheets %}
    {{ encore_entry_link_tags('app') }}
    {% set selectedTheme = app.user.preferredTheme ?? layout.uiTheme %}
    {% if isDarkModed is same as(true) %}
        {{ encore_entry_link_tags('app-theme-' ~ selectedTheme ~ '-dark') }}
    {% else %}
        {{ encore_entry_link_tags('app-theme-' ~ selectedTheme ~ '-light') }}
    {% endif %}
{% endblock %}

templates/layout/partials/_locale_switcher.html.twig
<li class="nav-item dropdown-language dropdown me-2 me-xl-0">
    <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
        <i class="bx bx-globe bx-sm"></i>
    </a>
    <ul class="dropdown-menu dropdown-menu-end">
        {% for appFallbackLocale in layout.locales %}
        <li>
            <a class="dropdown-item" href="{{ path('app_admin_profile_switch_locale_to', { fallback: appFallbackLocale.fallback }) }}">
                <span class="align-middle">{{ appFallbackLocale.name }}</span>
            </a>
        </li>
        {% endfor %}
    </ul>
</li>

templates/layout/partials/_logo.html.twig
<span class="app-brand-logo demo">
  {% include 'layout/partials/_logo_svg.html.twig' %}
</span>
<span class="app-brand-text demo menu-text fw-bold ms-2">{{ layout.admin.logoText }}</span>

templates/layout/partials/_notifications.html.twig
{{ component('_notification_component') }}

templates/layout/partials/_search.html.twig
<div class="navbar-nav align-items-center">
    <div class="nav-item navbar-search-wrapper mb-0">
        <a class="nav-item nav-link search-toggler px-0" href="{{ path('app_admin_search_index') }}">
            <i class="bx bx-search-alt bx-sm"></i>
            <span class="d-none d-md-inline-block">{{ 'Ara'|trans }} (Ctrl+U)</span>
        </a>
    </div>
</div>

templates/layout/partials/_sidebar.html.twig
{% for menuItem in appAdminMenu(app.user) %}
    {% if menuItem.type is same as("section") %}
        <li class="menu-header small text-uppercase" id="menu_section_{{ menuItem.label }}">
            <span class="menu-header-text">{{ menuItem.label }}</span>
        </li>
    {% endif %}
    {% if menuItem.type is same as("route") %}
        <li class="menu-item" id="menu_item_{{ menuItem.label|replace({' ': ''}) }}">
            <a href="{{ path(menuItem.routeName, menuItem.routeParameters) }}" class="menu-link" target="{{ menuItem.linkTarget }}">
                <i class="menu-icon tf-icons {{ menuItem.icon }}"></i>
                <div>{{ menuItem.label }}</div>
                {% if menuItem.badge is not same as(null) %}
                    <div class="badge bg-primary rounded-pill ms-auto">{{ menuItem.badge.content }}</div>
                {% endif %}
            </a>
        </li>
    {% endif %}
    {% if menuItem.type is same as("submenu") %}
        <li class="menu-item" id="menu_item_{{ menuItem.label|replace({' ': ''}) }}">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons {{ menuItem.icon }}"></i>
                <div>{{ menuItem.label }}</div>
                {% if menuItem.badge is not same as(null) %}
                    <div class="badge bg-primary rounded-pill ms-auto">{{ menuItem.badge.content }}</div>
                {% endif %}
            </a>
            <ul class="menu-sub">
                {% for subItem in menuItem.subItems %}
                    <li class="menu-item" id="menu_item_{{ subItem.label|replace({' ': ''}) }}">
                        <a href="{{ path(subItem.routeName, subItem.routeParameters) }}" class="menu-link">
                            <div>{{ subItem.label }}</div>
                            {% if subItem.badge is not same as(null) %}
                                <div class="badge bg-primary rounded-pill ms-auto">{{ subItem.badge.content }}</div>
                            {% endif %}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </li>
    {% endif %}
{% endfor %}

templates/layout/partials/_style_switcher.html.twig
<li class="nav-item dropdown-style-switcher dropdown me-2 me-xl-0">
    <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
        <i class="bx bx-sm {% if app.user.darkMode is same as(true) %}bx-moon{% else %}bx-sun{% endif %}"></i>
    </a>
    <ul class="dropdown-menu dropdown-menu-end dropdown-styles">
        <li>
            <a class="dropdown-item" href="{{ path('app_admin_profile_switch_to_light_mode') }}" data-theme="light">
                <span class="align-middle"><i class="bx bx-sun me-2"></i>{{ 'Aydınlık Tema'|trans }}</span>
            </a>
        </li>
        <li>
            <a class="dropdown-item" href="{{ path('app_admin_profile_switch_to_dark_mode') }}" data-theme="dark">
                <span class="align-middle"><i class="bx bx-moon me-2"></i>{{ 'Karanlık Tema'|trans }}</span>
            </a>
        </li>
        <li>
            <a href="#" class="dropdown-item" data-bs-toggle="offcanvas" data-bs-target="#themeSwitcherOffCanvas">
                <span class="align-middle"><i class="bx bx-layout me-2"></i>{{ 'Tema Değiştir'|trans }}</span>
            </a>
        </li>
    </ul>
</li>

templates/layout/partials/_theme_switcher.html.twig
<div class="row">

    <!-- Default Theme -->
    <div class="col-md-6 mt-2">
        <div class="bg-white rounded p-1">
            <div class="d-flex justify-content-center my-2">
                <span class="text-muted small">{{ 'Varsayılan'|trans }}</span>
            </div>
            <a href="{{ path('app_admin_profile_change_theme', { theUser: app.user.id, _theme: "default" }) }}">
                <img class="card-img-top" src="{{ asset('build/media/layouts/default.svg') }}" alt="{{ 'Varsayılan Tema'|trans }}" />
            </a>
        </div>
    </div>

    <!-- Bordered Theme -->
    <div class="col-md-6 mt-2">
        <div class="bg-white rounded p-1">
            <div class="d-flex justify-content-center my-2">
                <span class="text-muted small">{{ 'Kenarlıklı'|trans }}</span>
            </div>
            <a href="{{ path('app_admin_profile_change_theme', { theUser: app.user.id, _theme: "bordered" }) }}">
                <img class="card-img-top" src="{{ asset('build/media/layouts/bordered.svg') }}" alt="{{ 'Kenarlıklı Tema'|trans }}" />
            </a>
        </div>
    </div>

    <!-- Raspberry Theme -->
    <div class="col-md-6 mt-2">
        <div class="bg-white rounded p-1">
            <div class="d-flex justify-content-center my-2">
                <span class="text-muted small">{{ 'Renkli'|trans }}</span>
            </div>
            <a href="{{ path('app_admin_profile_change_theme', { theUser: app.user.id, _theme: "raspberry" }) }}">
                <img class="card-img-top" src="{{ asset('build/media/layouts/raspberry.svg') }}" alt="{{ 'Renkli Tema'|trans }}" />
            </a>
        </div>
    </div>

    <!-- Semidark Theme -->
    <div class="col-md-6 mt-2">
        <div class="bg-white rounded p-1">
            <div class="d-flex justify-content-center my-2">
                <span class="text-muted small">{{ 'Karanlık'|trans }}</span>
            </div>
            <a href="{{ path('app_admin_profile_change_theme', { theUser: app.user.id, _theme: "semidark" }) }}">
                <img class="card-img-top" src="{{ asset('build/media/layouts/semidark.svg') }}" alt="{{ 'Karanlık Tema' }}" />
            </a>
        </div>
    </div>

</div>

templates/layout/partials/_user_avatar.html.twig
<div class="avatar avatar-online">
    <img src="{{ userMenu.avatarUrl }}" alt="{{ 'Profil' }}" class="rounded-circle" />
</div>

templates/layout/partials/_usermenu.html.twig
<li>
    <a class="dropdown-item" href="#">
        <div class="d-flex">
            <div class="flex-shrink-0 me-3">
                {{ include('layout/partials/_user_avatar.html.twig') }}
            </div>
            <div class="flex-grow-1">
                <span class="fw-medium d-block lh-1">{{ userMenu.name }}</span>
                <small>{{ 'Hesap Adı'|trans }}</small>
            </div>
        </div>
    </a>
</li>
{% for userMenuItem in userMenu.items %}
    {% if userMenuItem.type is same as("section") %}
        <li>
            <div class="dropdown-divider"></div>
        </li>
    {% endif %}
    {% if userMenuItem.type is same as("logout") %}
        <li>
            <a class="dropdown-item" href="{{ path('app_auth_signout') }}">
                <i class="{{ userMenuItem.icon}} me-2"></i>
                <span class="align-middle">{{ userMenuItem.label }}</span>
            </a>
        </li>
    {% endif %}
    {% if userMenuItem.type is same as("route") %}
        <li>
            <a class="dropdown-item" href="{{ path(userMenuItem.routeName, userMenuItem.routeParameters) }}">
                <i class="{{ userMenuItem.icon }} me-2"></i>
                <span class="align-middle">{{ userMenuItem.label }}</span>
            </a>
        </li>
    {% endif %}
    {% if userMenuItem.type is same as("exit_impersonation") %}
        {% if is_granted('IS_IMPERSONATOR') %}
            <li>
                <a class="dropdown-item" href="{{ impersonation_exit_path(path('app_auth_signin') ) }}">
                    <i class="{{ userMenuItem.icon }} me-2"></i>
                    <span class="align-middle">{{ userMenuItem.label }}</span>
                </a>
            </li>
        {% endif %}
    {% endif %}
{% endfor %}