src/Entity/SubscriptionPlan.php
<?php

namespace App\Entity;

use App\Repository\SubscriptionPlanRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SubscriptionPlanRepository::class)]
class SubscriptionPlan
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $key_name = null;

    #[ORM\Column(length: 5)]
    private ?string $currency = null;

    #[ORM\Column]
    private ?int $payment_interval = null;

    #[ORM\Column]
    private ?int $trial_period_days = null;

    #[ORM\Column(length: 20)]
    private ?string $name = null;

    #[ORM\Column]
    private ?float $amount = null;

    #[ORM\Column(nullable: true)]
    private ?int $discount_percent = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_popular = null;

    #[ORM\Column(length: 10)]
    private ?string $currency_sign = null;

    #[ORM\Column]
    private ?int $plan_order = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $included_features = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $not_included_features = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getKeyName(): ?string
    {
        return $this->key_name;
    }

    public function setKeyName(string $key_name): static
    {
        $this->key_name = $key_name;

        return $this;
    }

    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    public function setCurrency(string $currency): static
    {
        $this->currency = $currency;

        return $this;
    }

    public function getPaymentInterval(): ?int
    {
        return $this->payment_interval;
    }

    public function setPaymentInterval(int $payment_interval): static
    {
        $this->payment_interval = $payment_interval;

        return $this;
    }

    public function getTrialPeriodDays(): ?int
    {
        return $this->trial_period_days;
    }

    public function setTrialPeriodDays(int $trial_period_days): static
    {
        $this->trial_period_days = $trial_period_days;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getDiscountPercent(): ?int
    {
        return $this->discount_percent;
    }

    public function setDiscountPercent(?int $discount_percent): static
    {
        $this->discount_percent = $discount_percent;

        return $this;
    }

    public function isIsPopular(): ?bool
    {
        return $this->is_popular;
    }

    public function setIsPopular(?bool $is_popular): static
    {
        $this->is_popular = $is_popular;

        return $this;
    }


    public function getCurrencySign(): ?string
    {
        return $this->currency_sign;
    }

    public function setCurrencySign(string $currency_sign): static
    {
        $this->currency_sign = $currency_sign;

        return $this;
    }

    public function getPlanOrder(): ?int
    {
        return $this->plan_order;
    }

    public function setPlanOrder(int $plan_order): static
    {
        $this->plan_order = $plan_order;

        return $this;
    }

    public function getIncludedFeatures(): ?string
    {
        return $this->included_features;
    }

    public function setIncludedFeatures(string $included_features): static
    {
        $this->included_features = $included_features;

        return $this;
    }

    public function getNotIncludedFeatures(): ?string
    {
        return $this->not_included_features;
    }

    public function setNotIncludedFeatures(?string $not_included_features): static
    {
        $this->not_included_features = $not_included_features;

        return $this;
    }

}

src/Entity/Team.php
<?php

namespace App\Entity;

use App\Repository\TeamRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: TeamRepository::class)]
class Team
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $name = null;

    #[ORM\Column(nullable: true)]
    private ?DateTimeImmutable $created_at = null;

    #[ORM\OneToMany(targetEntity: TeamInvite::class, mappedBy: 'team')]
    private Collection $teamInvites;

    #[ORM\OneToMany(targetEntity: User::class, mappedBy: 'team')]
    private Collection $users;

    #[ORM\Column(nullable: true)]
    private ?int $owner_id = null;

    public function __construct()
    {
        $this->teamInvites = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(?DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        if ($this->created_at === NULL) {
            $this->created_at = new DateTimeImmutable();
        }
    }

    /**
     * @return Collection<int, TeamInvite>
     */
    public function getTeamInvites(): Collection
    {
        return $this->teamInvites;
    }

    public function addTeamInvite(TeamInvite $teamInvite): static
    {
        if (!$this->teamInvites->contains($teamInvite)) {
            $this->teamInvites->add($teamInvite);
            $teamInvite->setTeam($this);
        }

        return $this;
    }

    public function removeTeamInvite(TeamInvite $teamInvite): static
    {
        if ($this->teamInvites->removeElement($teamInvite)) {
            // set the owning side to null (unless already changed)
            if ($teamInvite->getTeam() === $this) {
                $teamInvite->setTeam(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setTeam($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getTeam() === $this) {
                $user->setTeam(null);
            }
        }

        return $this;
    }

    public function getOwnerId(): ?int
    {
        return $this->owner_id;
    }

    public function setOwnerId(?int $owner_id): static
    {
        $this->owner_id = $owner_id;

        return $this;
    }

}

templates/component/_alert.html.twig
<div class="alert alert-{% if type is defined %}{{ type }}{% endif%} alert-dismissible" role="alert">
    {% if text is defined %}
        {{ text|raw }}
    {% endif %}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="{{ 'Kapat'|trans }}"></button>
</div>

templates/component/_alert_component.html.twig
<div class="alert alert-{% if type is defined %}{{ type }}{% endif%} alert-dismissible" role="alert">
    {% if text is defined %}
        {{ text|raw }}
    {% endif %}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="{{ 'Kapat'|trans }}"></button>
</div>

templates/component/_card_action_footer.html.twig
<div class="card-body">
    <div class="d-flex justify-content-end">
        {% set btnText = label is defined ? label : 'Kaydet'|trans %}
        {% set btnIcon = icon is defined ? icon : '' %}
        {% set btnType = type is defined ? type : 'primary' %}

        <button type="submit" class="btn btn-{{ btnType }}">
            <i class="{{ btnIcon }}"></i> {{ btnText }}
        </button>
    </div>
</div>

templates/component/_card_action_footer_component.html.twig
<div class="card-body">
    <div class="d-flex justify-content-end">
        {% set btnText = label is defined ? label : 'Kaydet'|trans %}
        {% set btnIcon = icon is defined ? icon : '' %}
        {% set btnType = type is defined ? type : 'primary' %}

        <button type="submit" class="btn btn-{{ btnType }}">
            <i class="{{ btnIcon }}"></i> {{ btnText }}
        </button>
    </div>
</div>

templates/component/_crud_table.html.twig
{% if debug is defined %}
    {% if debug is same as(true) and is_granted('ROLE_ADMIN') %}
        {{ dump(table) }}
    {% endif %}
{% endif %}

{% set tableID = table.options.stateSave|u.camel.title %}
<!-- [TABLE DECORATOR] : {{ title }} -->
<input type="hidden" class="crudTableDecorator"
       data-target="#{{ tableID }}"
       data-options='{{ datatable_settings(table) }}'
       data-path="{{ path('crudtable_callback') }}"
       data-fqcn="{{ table.options.stateSave }}"
       data-language='{{ datatable_language(table) }}'>

<!-- Chase -->


<!-- [TABLE] : {{ title }}  -->
<div class="card card-action">

    <div class="card-img-overlay d-flex justify-content-center align-items-center" id="crudLoaderCardOverlay">
        <div class="sk-chase sk-primary sk-center">
            <div class="sk-chase-dot"></div>
            <div class="sk-chase-dot"></div>
            <div class="sk-chase-dot"></div>
            <div class="sk-chase-dot"></div>
            <div class="sk-chase-dot"></div>
            <div class="sk-chase-dot"></div>
        </div>
    </div>

    <div class="card-header ">
        <h5 class="card-action-title">{{ title }}</h5>
        <div class="card-action-element">
            <ul class="list-inline mb-0">
                <li class="list-inline-item">
                    <a href="#{{ tableID }}OffCanvas" class="card-table-configurator" data-bs-toggle="offcanvas" ><i class="tf-icons bx bx-cog"></i></a>
                </li>
                <li class="list-inline-item">
                    <a href="javascript:void(0);" class="card-collapsible"><i class="tf-icons bx bx-chevron-up"></i></a>
                </li>
                <li class="list-inline-item">
                    <a href="javascript:void(0);" class="card-expand"><i class="tf-icons bx bx-fullscreen"></i></a>
                </li>
                <li class="list-inline-item">
                    <a href="javascript:void(0);" class="card-close"><i class="tf-icons bx bx-x"></i></a>
                </li>
            </ul>
        </div>
    </div>
    <div class="collapse show">
        <div class="card-datatable table-responsive pt-0 crudTableFixMinH">
            <table id="{{ tableID }}" class="dt-responsive table table-bordered">

            </table>
        </div>
    </div>
</div>

<!-- [TABLE CONFIGURATOR] : {{ title }} -->
<div class="offcanvas offcanvas-end" tabindex="-1" id="{{ tableID }}OffCanvas" aria-labelledby="{{ tableID }}OffCanvasLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="{{ tableID }}OffCanvasLabel">{{ 'Tabloyu Özelleştir' }}</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="{{ 'Kapat'|trans }}"></button>
    </div>
    <div class="offcanvas-body">
        <div class="alert alert-warning">
            {{ 'Bu tablo için hiçbir özelleştirme seçeneği sunulmadı.' }}
        </div>
    </div>
</div>

templates/component/_crud_table_component.html.twig
{% if debug is defined %}
    {% if debug is same as(true) and is_granted('ROLE_ADMIN') and app.environment is same as("dev") %}
        {# DEPRECED dump(table) #}
    {% endif %}
{% endif %}

{% set tableID = table.options.stateSave|u.camel.title %}
<!-- [TABLE DECORATOR] : {{ title }} -->
<input type="hidden" class="crudTableDecorator"
       data-target="#{{ tableID }}"
       data-options='{{ datatable_settings(table) }}'
       data-path="{{ path('crudtable_callback') }}"
       data-fqcn="{{ table.options.stateSave }}"
       data-language='{{ datatable_language(table) }}'>

<!-- Chase -->


<!-- [TABLE] : {{ title }}  -->
<div class="card card-action">

    <div class="card-img-overlay d-flex justify-content-center align-items-center" id="crudLoaderCardOverlay">
        <div class="sk-chase sk-primary sk-center">
            <div class="sk-chase-dot"></div>
            <div class="sk-chase-dot"></div>
            <div class="sk-chase-dot"></div>
            <div class="sk-chase-dot"></div>
            <div class="sk-chase-dot"></div>
            <div class="sk-chase-dot"></div>
        </div>
    </div>

    <div class="card-header ">
        <h5 class="card-action-title">{{ title }}</h5>
        <div class="card-action-element">
            <ul class="list-inline mb-0">
                <li class="list-inline-item">
                    <a href="#{{ tableID }}OffCanvas" class="card-table-configurator" data-bs-toggle="offcanvas" ><i class="tf-icons bx bx-cog"></i></a>
                </li>
                <li class="list-inline-item">
                    <a href="javascript:void(0);" class="card-collapsible"><i class="tf-icons bx bx-chevron-up"></i></a>
                </li>
                <li class="list-inline-item">
                    <a href="javascript:void(0);" class="card-expand"><i class="tf-icons bx bx-fullscreen"></i></a>
                </li>
                <li class="list-inline-item">
                    <a href="javascript:void(0);" class="card-close"><i class="tf-icons bx bx-x"></i></a>
                </li>
            </ul>
        </div>
    </div>
    <div class="collapse show">
        <div class="card-datatable table-responsive pt-0 crudTableFixMinH">
            <table id="{{ tableID }}" class="dt-responsive table table-bordered">

            </table>
        </div>
    </div>
</div>

<!-- [TABLE CONFIGURATOR] : {{ title }} -->
<div class="offcanvas offcanvas-end" tabindex="-1" id="{{ tableID }}OffCanvas" aria-labelledby="{{ tableID }}OffCanvasLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="{{ tableID }}OffCanvasLabel">{{ 'Tabloyu Özelleştir' }}</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="{{ 'Kapat'|trans }}"></button>
    </div>
    <div class="offcanvas-body">
        <div class="alert alert-warning">
            {{ 'Bu tablo için hiçbir özelleştirme seçeneği sunulmadı.' }}
        </div>
    </div>
</div>

templates/component/_notification_component.html.twig
<div {{ attributes }} data-poll>
    <li class="nav-item dropdown-notifications navbar-dropdown dropdown me-3 me-xl-2">
        <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
            <i class="bx bx-bell bx-sm"></i>
            {% if this.latestNotificationsCount > 0 %}
                <span class="badge bg-danger rounded-pill badge-notifications" >{{ this.latestNotificationsCount }}</span>
            {% endif %}
        </a>
        <ul class="dropdown-menu dropdown-menu-end py-0">
            <li class="dropdown-menu-header border-bottom">
                <div class="dropdown-header d-flex align-items-center py-3">
                    <h5 class="text-body mb-0 me-auto">{{ 'Son Bildirimler'|trans }}</h5>
                    {% if this.latestNotificationsCount > 0 %}
                        <a href="{{ path('app_admin_notification_mark_as_read_all') }}" class="dropdown-notifications-all text-body" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ 'Tümünü okundu işaretle'|trans }}">
                            <i class="bx fs-4 bx-envelope-open"></i>
                        </a>
                    {% endif %}
                </div>
            </li>
            <li class="dropdown-notifications-list scrollable-container">
                <ul class="list-group list-group-flush">
                    {% for notification in this.latestNotifications %}
                        <li class="list-group-item list-group-item-action dropdown-notifications-item">
                            <div class="d-flex">
                                <div class="flex-shrink-0 me-3">
                                    <div class="avatar">
                                        {% if notification.priority|upper is same as("LOW") %}
                                            <span class="avatar-initial rounded-circle bg-label-secondary"><i class="bx bx-info-circle"></i></span>
                                        {% elseif notification.priority|upper is same as("NORMAL") %}
                                            <span class="avatar-initial rounded-circle bg-label-info"><i class="bx bx-alarm-exclamation"></i></span>
                                        {% elseif notification.priority|upper is same as("HIGH") %}
                                            <span class="avatar-initial rounded-circle bg-label-danger"><i class="bx bx-error"></i></span>
                                        {% else %}
                                            <span class="avatar-initial rounded-circle bg-label-secondary"><i class="bx bx-info-circle"></i></span>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="flex-grow-1">
                                    <h6 class="mb-1">
                                        <a href="{% if notification.url is not same as(null) %}{{ notification.url }}{% else %}#{% endif %}">
                                            {% if notification.priority|upper is same as("LOW") %}
                                                {{ 'Düşük Öncelikli Bildirim'|trans }}
                                            {% elseif notification.priority|upper is same as("NORMAL") %}
                                                {{ 'Bildirim'|trans }}
                                            {% elseif notification.priority|upper is same as("HIGH") %}
                                                {{ 'Öncelikli Bildirim'|trans }}
                                            {% else %}
                                                {{ 'Yeni Bildirim'|trans }}
                                            {% endif %}
                                        </a>
                                    </h6>
                                    <p class="mb-0">{{ notification.content }}</p>
                                    <small class="text-muted">{{ notification.createdAt|ago }}</small>
                                </div>
                                <div class="flex-shrink-0 dropdown-notifications-actions">
                                    <a href="{{ path('app_admin_notification_mark_as_read', { notification: notification.id }) }}" class="dropdown-notifications-read"><span class="badge badge-dot"></span></a>
                                    <a href="{{ path('app_admin_notification_remove',  { notification: notification.id }) }}" class="dropdown-notifications-archive"><span class="bx bx-x"></span></a>
                                </div>
                            </div>
                        </li>
                    {% else %}
                        <div class="d-flex justify-content-center m-4">
                            <span class="text-warning"><i class="bx bx-sad"></i> {{ 'Burada hiçbir şey yok'|trans }}</span>
                        </div>
                    {% endfor %}
                </ul>
            </li>
            <li class="dropdown-menu-footer border-top">
                <a href="{{ path('app_admin_notification_index') }}" class="dropdown-item d-flex justify-content-center p-3">
                    {{ 'Tüm bildirimleri görüntüle'|trans }}
                </a>
            </li>
        </ul>
    </li>
</div>

templates/component/_subscription_plan.html.twig
<!-- Subscription Details -->
<div class="col-lg mb-md-0 mb-4">
    <div class="card {% if plan.isPopular is same as(true) %}border border-2 border-primary{% endif %}">
        <div class="card-body">

            <!-- Subscription Plan Title -->
            {% if plan.isPopular is same as(true) %}
                <div class="d-flex justify-content-between flex-wrap mb-3">
                    <h5 class="text-start text-uppercase mb-0">
                        {{ plan.name }}{% if plan.discountPercent is not same as(null) %} / %{{ plan.discountPercent}} {{ 'indirim'|trans }}{% endif%}
                    </h5>
                    <span class="badge bg-primary rounded-pill">{{ 'Popüler'|trans }}</span>
                </div>
            {% else %}
                <h5 class="text-start text-uppercase">
                    {{ plan.name }}{% if plan.discountPercent is not same as(null) %} / %{{ plan.discountPercent}} {{ 'indirim'|trans }}{% endif%}
                </h5>
            {% endif %}

            <!-- Subscription Plan Pricing -->
            <div class="text-center position-relative mb-4 pb-1">
                <div class="mb-2 d-flex">
                    <h1 class="price-toggle text-primary price-yearly mb-0">
                        {% if trialUsed is defined and trialUsed is not same as(true) %}
                            <small>
                                <del class="text-muted">
                                    {{ plan.currencySign}} {{ plan.amount }}
                                </del>
                            </small>
                            {{ plan.currencySign}} 0
                        {% else %}
                            {{ plan.currencySign}} {{ plan.amount }}
                        {% endif %}
                    </h1>
                    <sub class="h5 text-muted pricing-duration mt-auto mb-2">
                        /{% if plan.paymentInterval == 30 %}{{ 'ay'|trans }}{% else %}{{ plan.paymentInterval }}{{ 'gün'|trans }}{% endif %}
                    </sub>
                </div>
                <small class="position-absolute start-0 m-auto price-yearly price-yearly-toggle text-muted">
                    {{ plan.trialPeriodDays }} {{ 'gün ücretsiz deneyin'|trans }}
                </small>
            </div>

            <p>{{ 'Plan fiyatına vergiler dahildir.'|trans }}</p>

            <hr />

            <ul class="list-unstyled pt-2 pb-1">

                <!-- Subscription Plan Included Features -->
                {% for planFeature in plan.planFeatures %}
                    <li class="mb-2">
                            <span class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2">
                                <i class="bx bx-check bx-xs"></i>
                            </span>
                        {{ planFeature }}
                    </li>
                {% endfor %}

                <!-- Subscription Plan Not Included Features -->
                {% for planFeature in plan.planFeaturesNotIncluded %}
                    <li class="mb-2">
                                <span class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-secondary me-2">
                                    <i class="bx bx-x fs-5 lh-1"></i>
                                </span>
                        {{ planFeature }}
                    </li>
                {% endfor %}
            </ul>

            {% if hideActions is not defined %}
                <!-- Subscription Plan Get Started Button -->
                {% if plan.isPopular is same as(true) %}
                    <a href="{{ path('app_admin_exclude_subscription_plan_subscribe_plan', { thePlan: plan.id }) }}" class="btn btn-primary d-grid w-100">
                        {% if trialUsed is defined and trialUsed is not same as(true) %}
                            {{ 'Hemen Ücretsiz Deneyin'|trans }}
                        {% else %}
                            {{ 'Hemen Başlayın'|trans }}
                        {% endif %}
                    </a>
                {% else %}
                    <a href="{{ path('app_admin_exclude_subscription_plan_subscribe_plan', { thePlan: plan.id }) }}" class="btn btn-label-primary d-grid w-100" >
                        {% if trialUsed is defined and trialUsed is not same as(true) %}
                            {{ 'Hemen Ücretsiz Deneyin'|trans }}
                        {% else %}
                            {{ 'Hemen Başlayın'|trans }}
                        {% endif %}</a>
                {% endif %}
            {% endif %}

        </div>
    </div>
</div>
<!--/ Subscription Details -->

templates/component/_subscription_plan_component.html.twig
<!-- Subscription Details -->
<div class="col-lg mb-md-0 mb-4">
    <div class="card {% if plan.isPopular is same as(true) %}border border-2 border-primary{% endif %}">
        <div class="card-body">

            <!-- Subscription Plan Title -->
            {% if plan.isPopular is same as(true) %}
                <div class="d-flex justify-content-between flex-wrap mb-3">
                    <h5 class="text-start text-uppercase mb-0">
                        {{ plan.name }}{% if plan.discountPercent is not same as(null) %} / %{{ plan.discountPercent}} {{ 'indirim'|trans }}{% endif%}
                    </h5>
                    <span class="badge bg-primary rounded-pill">{{ 'Popüler'|trans }}</span>
                </div>
            {% else %}
                <h5 class="text-start text-uppercase">
                    {{ plan.name }}{% if plan.discountPercent is not same as(null) %} / %{{ plan.discountPercent}} {{ 'indirim'|trans }}{% endif%}
                </h5>
            {% endif %}

            <!-- Subscription Plan Pricing -->
            <div class="text-center position-relative mb-4 pb-1">
                <div class="mb-2 d-flex">
                    <h1 class="price-toggle text-primary price-yearly mb-0">
                        {% if trialUsed is defined and trialUsed is not same as(true) %}
                            <small>
                                <del class="text-muted">
                                    {{ plan.currencySign}} {{ plan.amount }}
                                </del>
                            </small>
                            {{ plan.currencySign}} 0
                        {% else %}
                            {{ plan.currencySign}} {{ plan.amount }}
                        {% endif %}
                    </h1>
                    <sub class="h5 text-muted pricing-duration mt-auto mb-2">
                        /{% if plan.paymentInterval == 30 %}{{ 'ay'|trans }}{% else %}{{ plan.paymentInterval }}{{ 'gün'|trans }}{% endif %}
                    </sub>
                </div>
                <small class="position-absolute start-0 m-auto price-yearly price-yearly-toggle text-muted">
                    {{ plan.trialPeriodDays }} {{ 'gün ücretsiz deneyin'|trans }}
                </small>
            </div>

            <p>{{ 'Plan fiyatına vergiler dahildir.'|trans }}</p>

            <hr />

            <ul class="list-unstyled pt-2 pb-1">

                <!-- Subscription Plan Included Features -->
                {% for planFeature in plan.includedFeatures|split(',') %}
                    <li class="mb-2">
                            <span class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-primary me-2">
                                <i class="bx bx-check bx-xs"></i>
                            </span>
                        {{ planFeature }}
                    </li>
                {% endfor %}

                <!-- Subscription Plan Not Included Features -->
                {% for planFeature in plan.notIncludedFeatures|split(",") %}
                    <li class="mb-2">
                                <span class="badge badge-center w-px-20 h-px-20 rounded-pill bg-label-secondary me-2">
                                    <i class="bx bx-x fs-5 lh-1"></i>
                                </span>
                        {{ planFeature }}
                    </li>
                {% endfor %}
            </ul>

            {% if hideActions is not defined %}
                <!-- Subscription Plan Get Started Button -->
                {% if plan.isPopular is same as(true) %}
                    <a href="{{ path('app_admin_exclude_subscription_plan_subscribe_plan', { thePlan: plan.id }) }}" class="btn btn-primary d-grid w-100">
                        {% if trialUsed is defined and trialUsed is not same as(true) %}
                            {{ 'Hemen Ücretsiz Deneyin'|trans }}
                        {% else %}
                            {{ 'Hemen Başlayın'|trans }}
                        {% endif %}
                    </a>
                {% else %}
                    <a href="{{ path('app_admin_exclude_subscription_plan_subscribe_plan', { thePlan: plan.id }) }}" class="btn btn-label-primary d-grid w-100" >
                        {% if trialUsed is defined and trialUsed is not same as(true) %}
                            {{ 'Hemen Ücretsiz Deneyin'|trans }}
                        {% else %}
                            {{ 'Hemen Başlayın'|trans }}
                        {% endif %}</a>
                {% endif %}
            {% endif %}

        </div>
    </div>
</div>
<!--/ Subscription Details -->